---
name: fabric-network
version: 1.0.0
caName: ca.paycap.net
mspName: PeerMSP
client:
    organization: Pps
    connection:
        timeout:
            peer:
                endorser: '300'
            orderer: '300'
channels:
    general:
        orderers:
        - orderer.paycap.net
        peers:
            peer0.pps.paycap.net: {}
organizations:
    Pps:
        mspid: PeerMSP
        peers:
        - peer0.pps.paycap.net
        certificateAuthorities:
        - ca.paycap.net
orderers:
    orderer.paycap.net:
        url: grpc://orderer:7050
peers:
    peer0.pps.paycap.net:
        url: grpc://peer0:7051
certificateAuthorities:
    ca.paycap.net:
        url: http://ca:7054
        caName: ca.paycap.net
        registrarId: admin
